<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="content-type" content="text/html" charset="UTF-8" />
  <meta name="author" content="Martin ProkÅ¡" />
  <title>ct3d - python howto</title>
</head>

<body>
  <h1>Cosmetic Thread 3D from python console</h1>

  <p>
    At this moment (2024/05/27) I do not know how to make FreeCAD standard
    command copy to Python console. Therefore I have to describe how to use it.
  </p>

  <p>
    There is no one thread function, there are more types of threads.
    There are internal cosmetic threads and external cosmetic threads.
    There are Part WB type thread and PartDesign type threads.
  </p>


  <h2>Internal thread, Part version</h2>

  <p>
    Minimal usage - create some thread object at 0,0,0, without
    attachment and with default parameters and without Thread group.
  </p>
  
  <code>
import ct3d_params<br />
import cosmeticthread3d_part as ct3d_p<br />
<br />
thrName = 'TestThread'<br />
thrParams = ct3d_params.ct3di_params_class()<br />
doc = App.ActiveDocument<br />
aPart = None<br />
obj = ct3d_p.internal(thrName, thrParams, doc, aPart)<br />
</code>

  <p>
    Module with parameters definition is common for internal and
    external threads. But the parameters differ for internal and
    external threads. Do not overlook the
    ct3d<b>i</b>_params_class() - the <em>i</em> letter for internal one.
  </p>

  <p>
    Once You have thread created, You can modiffy it. You can
    apply Attachment, You can edit parameters and You can move
    it to active part or group.
  </p>

  <p>
    Help for the internal thread command:
  </p>

  <code>
internal(name, ct3di_prms, doc, aPart) -> obj<br />
<br />
It creates Cosmetic Thread 3D Internal (Part version)<br />
and returns obj.<br />
<br />
This function is mentioned to be used for object creation.<br />
<br />
name       - [string]             name of the object in the model tree<br />
ct3di_prms - [ct3di_params_class] parameters of the cosmetic thread<br />
doc        - [text link]          document for thread creating<br />
aPart      - [text link]          Part object for thread creating or None<br />
  </code>



  <h2>External thread, Part version</h2>

  <p>
  Minimal usage - create some thread object at 0,0,0, without attachment and
  with default parameters and without Thread group.
  </p>

  <code>
import ct3d_params<br />
import cosmeticthread3d_part as ct3d_p<br />
<br />
thrName = 'TestThread'<br />
thrParams = ct3d_params.ct3de_params_class()<br />
doc = App.ActiveDocument<br />
aPart = None<br />
obj = ct3d_p.external(thrName, thrParams, doc, aPart)<br />
  </code>

  <p>
  Do not overlook the ct3d<b>e</b>_params_class() - the <em>e</em> letter.
  </p>


  <h2>Internal thread, PartDesign version</h2>

  <p>
    This PartDesign version of Cosmetic Thread 3D is under developement.
    May be it will not be implemented in final version of CosmeticThread.
  </p>

  <p>
    Minimal usage - create some thread object at 0,0,0, without attachment and
    with default parameters.
  </p>

  <p>
    It is PartDesign version of cosmetic thread 3D - do not forget activate
    PD body first!
  </p>
  
  <code>
import ct3d_params<br />
import cosmeticthread3d_partdesign as ct3d_pd<br />
<br />
thrName = 'TestThread'<br />
thrParams = ct3d_params.ct3di_params_class()<br />
doc = App.ActiveDocument<br />
body = Gui.ActiveDocument.ActiveView.getActiveObject("pdbody")<br />
obj = ct3d_pd.internal(thrName, thrParams, doc, body)<br />
</code>

  <p>
    Module with parameters definition is common for internal and
    external threads. But the parameters differ for internal and
    external threads. Do not overlook the
    ct3d<b>i</b>_params_class() - the <em>i</em> letter for internal one.
  </p>

  <p>
    Once You have thread created, You can modiffy it. You can
    apply Attachment, You can edit parameters and You can move
    it to active part or group.
  </p>

  <p>
    Help for the internal thread command:
  </p>

  <code>
internal(name, ct3di_prms, doc, body) -> obj<br />
<br />
It creates Cosmetic Thread 3D Internal (PartDesign version)<br />
and returns obj.<br />
<br />
This function is mentioned to be used for object creation.<br />
<br />
name       - [string]           name of the object in the model tree<br />
ct3di_prms - [ct3di_params_class] parameters of the cosmetic thread<br />
doc        - [text link]              document for thread creating<br />
body       - [PartDesign body object] body object for the thread<br />
  </code>

  <h2>External thread, PartDesign version</h2>

  <p>
    This PartDesign version of Cosmetic Thread 3D is under developement.
    May be it will not be implemented in final version of CosmeticThread.
  </p>

  <p>
    Minimal usage - create some thread object at 0,0,0, without attachment and
    with default parameters.
  </p>
  
  <code>
import ct3d_params<br />
import cosmeticthread3d_partdesign as ct3d_pd<br />
<br />
thrName = 'TestThread'<br />
thrParams = ct3d_params.ct3de_params_class()<br />
doc = App.ActiveDocument<br />
body = Gui.ActiveDocument.ActiveView.getActiveObject("pdbody")<br />
obj = ct3d_pd.external_pd0(thrName, thrParams, doc, body)<br />
  </code>

  <p>
    Do not overlook the ct3d<b>e</b>_params_class() - the <em>e</em> letter.
  </p>


</body>
</html>
